const ClientData = [
  {
    id: "1",
    image: "assets/software-developer-g859bd614a_640.jpg",
    name: "Harpreet singh",
    company_name: "crowdmed",
    project_title:"Full stack software engineer",
    post: "CEO",
    project_category: "Web development",
    client_quote: "Very good developer. it was a long project the developer made all the work as expected. very talented i will work with him again soon. highly recommended",
  },
  {
    id: "2",
    image: "assets/engineer-g0460c8033_640.jpg",
    name: "Harpreet singh",
    company_name: "crowdmed",
    project_title:"Full stack software engineer",
    post: "CEO",
    project_category: "Web development",
    client_quote: "I worked with Gurpreet for 1 year and he has consistently been great and hard working. I highly recommend working with him",
  },
  {
    id: "3",
    image: "assets/student-gfa60f822a_640.jpg",
    name: "Harpreet singh",
    company_name: "crowdmed",
    project_title:"Full stack software engineer",
    post: "CEO",
    project_category: "Blockchain",
    client_quote: "Amazing communication and work ethic",
  },
  {
    id: "4",
    image: "assets/engineer-g0460c8033_640.jpg",
    name: "Harpreet singh",
    company_name: "crowdmed",
    project_title:"Full stack software engineer",
    post: "CEO",
    project_category: "Web development",
    client_quote: "Overall great working experience and completed the job quickly. Easy to communicate with and I would recommend working with Gurpreet to others",
  },
  {
    id: "5",
    image: "assets/software-developer-g859bd614a_640.jpg",
    name: "Harpreet singh",
    company_name: "crowdmed",
    project_title:"Full stack software engineer",
    post: "CEO",
    project_category: "Blockchain",
    client_quote: "Great work ethic and communication",
  },
  {
    id: "6",
    image: "assets/software-developer-g859bd614a_640.jpg",
    name: "Harpreet singh",
    company_name: "crowdmed",
    project_title:"Full stack software engineer",
    post: "CEO",
    project_category: "Web development",
    client_quote: "He is a great developer and do clean work fastly",
  },
  {
    id: "7",
    image: "assets/software-developer-g859bd614a_640.jpg",
    name: "Harpreet singh",
    company_name: "crowdmed",
    project_title:"Full stack software engineer",
    post: "CEO",
    project_category: "Mobile",
    client_quote: "The most professional, top skilled and great communicator! Guri did his job extremely well. I got the react-native project above than my expectations. Highly recommended!",
  },
  {
    id: "8",
    image: "assets/software-developer-g859bd614a_640.jpg",
    name: "Harpreet singh",
    company_name: "crowdmed",
    project_title:"Full stack software engineer",
    post: "CEO",
    project_category: "Mobile",
    client_quote: "Great communication and availability",
  },
  {
    id: "9",
    image: "assets/software-developer-g859bd614a_640.jpg",
    name: "Harpreet singh",
    company_name: "crowdmed",
    project_title:"Full stack software engineer",
    post: "CEO",
    project_category: "Web development",
    client_quote: "Guri is very skillful cooperative developer. He done his job well as a react native expert. Genuinely recommended!",
  },
  {
    id: "10",
    image: "assets/software-developer-g859bd614a_640.jpg",
    name: "Harpreet singh",
    company_name: "crowdmed",
    project_title:"Full stack software engineer",
    post: "CEO",
    project_category: "Web development",
    client_quote: "He is having excellent skills for Mobile app development. And high level communication. Very good person. Will hire him again soon.",
  },
]
export default ClientData;
