const ClientData = [
  {
    id: "1",
    image: "assets/software-developer-g859bd614a_640.jpg",
    name: "Harpreet singh",
    company_name: "crowdmed",
    post: "CEO",
    project_category: "Web development",
    client_quote: "He is a great developer",
  },
  {
    id: "2",
    image: "assets/technology-1283624__480.webp",
    name: "Harpreet singh",
    company_name: "crowdmed",
    post: "CEO",
    project_category: "Web development",
    client_quote: "He is a great developer",
  },
  {
    id: "3",
    image: "assets/student-gfa60f822a_640.jpg",
    name: "Harpreet singh",
    company_name: "crowdmed",
    post: "CEO",
    project_category: "Web development",
    client_quote: "He is a great developer",
  },
  {
    id: "4",
    image: "assets/engineer-g0460c8033_640.jpg",
    name: "Harpreet singh",
    company_name: "crowdmed",
    post: "CEO",
    project_category: "Web development",
    client_quote: "He is a great developer",
  },
  {
    id: "5",
    image: "assets/software-developer-g859bd614a_640.jpg",
    name: "Harpreet singh",
    company_name: "crowdmed",
    post: "CEO",
    project_category: "Web development",
    client_quote: "He is a great developer",
  },
  {
    id: "6",
    image: "assets/software-developer-g859bd614a_640.jpg",
    name: "Harpreet singh",
    company_name: "crowdmed",
    post: "CEO",
    project_category: "Web development",
    client_quote: "He is a great developer",
  },
]
export default ClientData;
